import Header from "@/components/Header";
import Head from "next/head";
import Script from "next/script";

import ContextRootProvider from "./ContextRootProvider";

export const metadata = {
  title: "Platzistore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script id="google-analytics" strategy="afterInteractive">
        {`window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            
            gtag('config', 'G-8V1QM1B3Y3');
            `}
      </Script>
      <Script
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-8V1QM1B3Y3"
        strategy="afterInteractive"
      ></Script>
      <body>
        <ContextRootProvider>
          <Header />
          {children}
        </ContextRootProvider>
      </body>
    </html>
  );
}
